fix(pre-commit): вернул pre-commit hook

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,1 +1,9 @@
 make lint
+
+returncode=$?
+if [ $returncode -ne 0 ]; then
+  echo "linter failed"
+  exit 1
+fi
+
+exit 0
